# 文件路径：intent_recognition/train_data.py

# -*- coding: utf-8 -*-

# 严格按照意图模式生成的大量、多样化、并可直接使用的训练数据（扩充版）
train_data = [
    # ==============================================================================
    # 意图 1: find_relation_by_two_entities
    # 模式: [实体A] + [实体B] -> 询问二者关系
    # ==============================================================================
    ("数组跟链表有什么关系", "find_relation_by_two_entities"),
    ("BFS和DFS之间有什么关联？", "find_relation_by_two_entities"),
    ("对比一下快速排序和归并排序", "find_relation_by_two_entities"),
    ("哈希表和散列表是同义的吗？", "find_relation_by_two_entities"),
    ("二叉搜索树是属于平衡二叉树的吗？", "find_relation_by_two_entities"),
    ("最小生成树和最短路径问题有何不同？", "find_relation_by_two_entities"),
    ("有向图和无向图的区别是什么？", "find_relation_by_two_entities"),
    ("堆和栈的差异", "find_relation_by_two_entities"),
    ("逻辑结构和物理结构有什么联系？", "find_relation_by_two_entities"),
    ("Prim算法和Kruskal算法都是解决最小生成树的吗？", "find_relation_by_two_entities"),
    ("递归和迭代哪个更好？", "find_relation_by_two_entities"),
    ("时间复杂度和空间复杂度是什么关系？", "find_relation_by_two_entities"),
    ("邻接表与邻接矩阵的比较", "find_relation_by_two_entities"),
    ("满二叉树和完全二叉树的关系", "find_relation_by_two_entities"),
    ("Dijkstra算法和Floyd算法都能求最短路径吗？", "find_relation_by_two_entities"),
    ("冒泡排序和选择排序哪个更稳定？", "find_relation_by_two_entities"),
    ("抽象数据类型和数据类型有什么区别？", "find_relation_by_two_entities"),
    ("大根堆和小根堆正好相反吗？", "find_relation_by_two_entities"),
    ("分治法和动态规划有何关联？", "find_relation_by_two_entities"),
    ("单链表和双向链表的主要差异是什么", "find_relation_by_two_entities"),
    ("比较一下线性结构和非线性结构", "find_relation_by_two_entities"),
    ("回溯法和DFS是什么关系", "find_relation_by_two_entities"),
    ("图的顶点和树的节点是类似的概念吗", "find_relation_by_two_entities"),
    ("队列和栈的操作效率对比", "find_relation_by_two_entities"),
    ("二分查找与二叉搜索树的联系", "find_relation_by_two_entities"),
    ("贪心策略和动态规划的区别", "find_relation_by_two_entities"),
    ("比较排序和基数排序的原理", "find_relation_by_two_entities"),
    ("稀疏图和稠密图的存储方式有何不同", "find_relation_by_two_entities"),
    ("AOV网和AOE网的应用场景差异", "find_relation_by_two_entities"),
    ("指针和引用的区别是什么？", "find_relation_by_two_entities"),
    ("邻接多重表和十字链表分别适用于什么类型的图？", "find_relation_by_two_entities"),
    ("直接插入排序和希尔排序的关系", "find_relation_by_two_entities"),
    ("平衡因子和树的高度有关系吗", "find_relation_by_two_entities"),
    ("连通图和强连通图的定义差异", "find_relation_by_two_entities"),
    ("循环队列和普通队列的对比", "find_relation_by_two_entities"),
    ("队列和栈在应用上有什么不同", "find_relation_by_two_entities"),
    ("谈谈数组和链表的优缺点", "find_relation_by_two_entities"),
    ("深度优先搜索和广度优先搜索的性能比较", "find_relation_by_two_entities"),
    ("普里姆算法与克鲁斯卡尔算法的异同", "find_relation_by_two_entities"),
    ("平衡二叉树和二叉搜索树的联系", "find_relation_by_two_entities"),
    ("邻接矩阵和邻接表分别适合什么场景", "find_relation_by_two_entities"),
    ("递归与分治策略的关系", "find_relation_by_two_entities"),
    ("顺序查找和二分查找哪个快", "find_relation_by_two_entities"),
    ("堆排序和快速排序的稳定性对比", "find_relation_by_two_entities"),
    ("动态规划和分治法有啥区别", "find_relation_by_two_entities"),
    ("聊聊邻接表和邻接矩阵的应用场景差异", "find_relation_by_two_entities"),
    ("二叉搜索树和红黑树哪个更复杂", "find_relation_by_two_entities"),
    ("哈希表与字典的联系", "find_relation_by_two_entities"),
    ("BFS 与 DFS 在空间使用上的对比", "find_relation_by_two_entities"),
    ("说说看Dijkstra算法和Floyd算法的共同点", "find_relation_by_two_entities"),
    ("选择排序和冒泡排序的效率比较", "find_relation_by_two_entities"),
    ("强连通图和弱连通图的定义有何不同", "find_relation_by_two_entities"),

    # ==============================================================================
    # 意图 2: find_entity_by_relation_and_entity
    # 模式: [实体A] + [关系] -> 询问相关的另一实体
    # ==============================================================================
    ("树这种结构包含哪些类型的节点？", "find_entity_by_relation_and_entity"),
    ("排序算法都具有哪些属性？", "find_entity_by_relation_and_entity"),
    ("图的遍历方法都有哪些", "find_entity_by_relation_and_entity"),
    ("告诉我几种不同的排序算法", "find_entity_by_relation_and_entity"),
    ("哈希表有哪些常用的冲突解决方法", "find_entity_by_relation_and_entity"),
    ("一个树节点由什么构成", "find_entity_by_relation_and_entity"),
    ("除了Dijkstra，还有哪些求最短路径的算法", "find_entity_by_relation_and_entity"),
    ("非线性结构都有什么例子", "find_entity_by_relation_and_entity"),
    ("图的组成部分除了顶点还有什么？", "find_entity_by_relation_and_entity"),
    ("和最小生成树问题相关的算法有哪些？", "find_entity_by_relation_and_entity"),
    ("线性结构包含哪些具体的数据结构？", "find_entity_by_relation_and_entity"),
    ("一个树的节点包含哪些部分？", "find_entity_by_relation_and_entity"),
    ("属于交换排序的有哪些具体算法？", "find_entity_by_relation_and_entity"),
    ("解决哈希冲突的方法有哪些？", "find_entity_by_relation_and_entity"),
    ("栈的常见操作有哪些？", "find_entity_by_relation_and_entity"),
    ("图的遍历算法除了BFS还有什么？", "find_entity_by_relation_and_entity"),
    ("时间复杂度这个属性通常有哪些衡量标准？", "find_entity_by_relation_and_entity"),
    ("实现一个队列需要哪些基本操作？", "find_entity_by_relation_and_entity"),
    ("无向图的存储结构除了邻接矩阵还有别的吗？", "find_entity_by_relation_and_entity"),
    ("最短路径算法除了迪杰斯特拉还有哪些", "find_entity_by_relation_and_entity"),
    ("树的遍历方式有几种", "find_entity_by_relation_and_entity"),
    ("常见的非线性结构有哪些例子", "find_entity_by_relation_and_entity"),
    ("一个算法的基本特征包括什么", "find_entity_by_relation_and_entity"),
    ("哈希函数的设计原则有哪些", "find_entity_by_relation_and_entity"),
    ("平衡二叉树的调整操作包括哪些", "find_entity_by_relation_and_entity"),
    ("简单排序都有哪些算法？", "find_entity_by_relation_and_entity"),
    ("图的存储除了邻接表还有啥？", "find_entity_by_relation_and_entity"),
    ("动态规划问题有什么共同特征？", "find_entity_by_relation_and_entity"),
    ("链表的节点由什么组成？", "find_entity_by_relation_and_entity"),
    ("求最小生成树的经典算法有哪些", "find_entity_by_relation_and_entity"),
    ("二叉树有哪些特殊的形态", "find_entity_by_relation_and_entity"),
    ("图的表示方法有哪些", "find_entity_by_relation_and_entity"),
    ("线性数据结构的例子有哪些", "find_entity_by_relation_and_entity"),
    ("二叉树的遍历方法除了前序还有哪些", "find_entity_by_relation_and_entity"),
    ("除了插入排序，还有哪些是稳定排序算法", "find_entity_by_relation_and_entity"),
    ("告诉我几种常见的哈希函数", "find_entity_by_relation_and_entity"),
    ("一个队列都支持哪些基本操作", "find_entity_by_relation_and_entity"),
    ("树的节点可以有哪些属性", "find_entity_by_relation_and_entity"),
    ("最短路径算法的种类", "find_entity_by_relation_and_entity"),
    ("除了用数组，还可以用什么实现栈", "find_entity_by_relation_and_entity"),
    ("动态规划具备的几个要素", "find_entity_by_relation_and_entity"),

    # ==============================================================================
    # 意图 3: find_entity_definition
    # 模式: 询问 [实体] 的定义、原理或描述
    # ==============================================================================
    ("什么是数组？", "find_entity_definition"),
    ("介绍一下快速排序", "find_entity_definition"),
    ("讲讲DFS的原理", "find_entity_definition"),
    ("请解释一下哈希表", "find_entity_definition"),
    ("什么是时间复杂度？", "find_entity_definition"),
    ("介绍下Dijkstra算法", "find_entity_definition"),
    ("什么叫“树的深度”", "find_entity_definition"),
    ("可以为我解释下“贪心算法”吗", "find_entity_definition"),
    ("“并查集”是用来做什么的", "find_entity_definition"),
    ("我想了解“快速排序”的实现细节", "find_entity_definition"),
    ("查询实体：堆", "find_entity_definition"),
    ("冒泡排序具体是怎么操作的", "find_entity_definition"),
    ("“哈希函数”指的是什么", "find_entity_definition"),
    ("我想了解下图", "find_entity_definition"),
    ("什么是递归？", "find_entity_definition"),
    ("讲一下动态规划的核心思想", "find_entity_definition"),
    ("平衡二叉树是什么", "find_entity_definition"),
    ("什么是并查集？", "find_entity_definition"),
    ("能讲讲拓扑排序吗", "find_entity_definition"),
    ("堆排序的原理是什么", "find_entity_definition"),
    ("说明一下邻接表的概念", "find_entity_definition"),
    ("解释下什么叫算法的稳定性", "find_entity_definition"),
    ("堆是什么样的数据结构", "find_entity_definition"),
    ("解释一下AOE网", "find_entity_definition"),
    ("我想学习一下KMP算法", "find_entity_definition"),
    ("什么是回溯法", "find_entity_definition"),
    ("可以讲讲并查集吗", "find_entity_definition"),
    ("查询“最小生成树”", "find_entity_definition"),
    ("告诉我关于“图”的知识", "find_entity_definition"),
    ("描述一下“队列”的特性", "find_entity_definition"),
    ("“栈”是怎么工作的", "find_entity_definition"),
    ("希尔排序的核心思想是什么", "find_entity_definition"),
    ("介绍下归并排序", "find_entity_definition"),
    ("能否说明白平衡因子是啥", "find_entity_definition"),
    ("线性表是什么", "find_entity_definition"),
    ("哈希表查询", "find_entity_definition"),
    ("B树", "find_entity_definition"),


    # ==============================================================================
    # 意图 4: other
    # 模式: 不符合以上模式的所有其他问题（例如：闲聊、主观问题等）
    # ==============================================================================
    ("数据结构难吗？", "other"),
    ("如何学好算法？", "other"),
    ("排序算法哪个最常用？", "other"),
    ("你好", "other"),
    ("台北今天天气怎么样？", "other"),
    ("现在几点了？", "other"),
    ("你是谁？", "other"),
    ("谢谢", "other"),
    ("再见", "other"),
    ("晚上好", "other"),
    ("你累了吗", "other"),
    ("学习这个有什么用", "other"),
    ("我应该从哪里开始", "other"),
    ("今天东京热吗", "other"),
    ("给我讲个笑话", "other"),
    ("有没有学习资料推荐", "other"),
    ("这个项目是谁开发的", "other"),
    ("不错", "other"),
    ("继续说", "other"),
    ("你还能做什么", "other"),
    ("你真厉害", "other"),
    ("有什么可以帮我的吗", "other"),
    ("今天是2025年8月22日吗？", "other"),
    ("这个知识库是谁做的", "other"),
    ("你都会做什么", "other"),
    ("哪个算法最好用", "other"),
    ("早上好", "other"),
    ("你叫什么名字", "other"),
    ("北京今天多少度", "other"),
    ("数据结构太难了", "other"),
    ("推荐一本算法书", "other"),
    ("代码写错了怎么办", "other"),
    ("你觉得Python是最好的语言吗", "other"),
    ("帮我做个计划", "other"),
    ("明天会下雨吗", "other"),
    ("我该如何开始学习", "other"),
    ("不客气", "other"),
    ("你是机器人吗", "other"),
    ("排序", "other"),
]

# 统计最终各类别的数量
intent_counts = {}
for _, intent in train_data:
    intent_counts[intent] = intent_counts.get(intent, 0) + 1

print("成功生成一份包含 {} 条样本的静态训练数据。".format(len(train_data)))
print("样本分布如下：")
for intent, count in intent_counts.items():
    print(f"- 意图 '{intent.replace('_', ' ')}': {count} 条样本")