batch_size: 16
class_weights: [8.571, 2.072, 0.799, 3.626, 0.220, 6.286, 6.286]
use_class_weights: true
early_stopping_patience: 6
epoch: 50
gpu_id: 0
gpu_ids: 0,1
learning_rate: 3e-4
log_interval: 10
lr_factor: 0.8
lr_patience: 3
only_comparison_plot: false
plot_utils: matplot
predict_plot: false
seed: 2
show_plot: false
train_log: true
use_gpu: true
use_multi_gpu: false
weight_decay: 1e-3
